import '../../modules/places/data/models/place_model.dart';

/// Central repository of high-quality sample data matching Phase 6.2 specifications.
class DemoData {
  DemoData._();

  static List<PlaceModel> get restaurants => [
        PlaceModel(
          id: 'demo-rest-1',
          name: 'Barbeque Nation',
          description: 'A premium dining experience pioneering the live on-the-table grill concept. Enjoy unlimited starters, a lavish buffet, and delicious desserts in a warm family environment.',
          category: 'BBQ',
          budget: '₹₹₹',
          location: 'Prahladnagar, Ahmedabad, Gujarat, India',
          rating: 4.6,
          isWishlist: false,
          isVisited: true,
          imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop',
          type: 'restaurant',
          latitude: 23.0121,
          longitude: 72.5076,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
        ),
        PlaceModel(
          id: 'demo-rest-2',
          name: "Tomato's",
          description: 'Retro 1950s American diner-style restaurant famous for its vintage decor, upbeat music, and delectable Mexican, Continental, and North Indian cuisines.',
          category: 'Multi Cuisine',
          budget: '₹₹',
          location: 'CG Road, Ahmedabad, Gujarat, India',
          rating: 4.4,
          isWishlist: true,
          isVisited: false,
          imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&auto=format&fit=crop',
          type: 'restaurant',
          latitude: 23.0298,
          longitude: 72.5621,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
        ),
        PlaceModel(
          id: 'demo-rest-3',
          name: 'The Blue Oven',
          description: 'Authentic wood-fired Neapolitan pizzeria serving artisanal sourdough pizzas, fresh salads, and Italian desserts made with imported San Marzano tomatoes.',
          category: 'Pizza',
          budget: '₹₹₹',
          location: 'Bodakdev, Ahmedabad, Gujarat, India',
          rating: 4.7,
          isWishlist: false,
          isVisited: true,
          imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop',
          type: 'restaurant',
          latitude: 23.0378,
          longitude: 72.5113,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
        ),
        PlaceModel(
          id: 'demo-rest-4',
          name: 'Honest',
          description: 'A beloved local street food chain legendary for its signature butter Pav Bhaji, Pulav, and North Indian thalis, serving millions of happy customers since 1975.',
          category: 'Street Food',
          budget: '₹',
          location: 'Satellite, Ahmedabad, Gujarat, India',
          rating: 4.3,
          isWishlist: false,
          isVisited: true,
          imageUrl: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop',
          type: 'restaurant',
          latitude: 23.0301,
          longitude: 72.5310,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
        ),
        PlaceModel(
          id: 'demo-rest-5',
          name: 'Gwalia Vanakkam',
          description: 'An elegant South Indian specialty dining experience offering a wide variety of crispy paper dosas, soft idlis, and authentic filter coffee in a premium environment.',
          category: 'South Indian',
          budget: '₹₹',
          location: 'Vastrapur, Ahmedabad, Gujarat, India',
          rating: 4.5,
          isWishlist: true,
          isVisited: false,
          imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop',
          type: 'restaurant',
          latitude: 23.0355,
          longitude: 72.5282,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
        ),
        PlaceModel(
          id: 'demo-rest-6',
          name: 'Agashiye',
          description: 'An iconic heritage Gujarati fine-dining destination set on the rooftop of the House of MG, serving a lavish, unlimited Gujarati thali that celebrates regional flavors.',
          category: 'Gujarati',
          budget: '₹₹₹',
          location: 'Lal Darwaja, Old City, Ahmedabad, Gujarat, India',
          rating: 4.8,
          isWishlist: false,
          isVisited: true,
          imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&auto=format&fit=crop',
          type: 'restaurant',
          latitude: 23.0267,
          longitude: 72.5815,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
        ),
        PlaceModel(
          id: 'demo-rest-7',
          name: 'Rajwadu',
          description: 'An ethnic village-themed restaurant showcasing local folk dances, live puppetry, and rich traditional dining options in a beautiful open-air courtyard.',
          category: 'Rajasthani',
          budget: '₹₹₹',
          location: 'Vejalpur, Ahmedabad, Gujarat, India',
          rating: 4.6,
          isWishlist: true,
          isVisited: false,
          imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&auto=format&fit=crop',
          type: 'restaurant',
          latitude: 22.9995,
          longitude: 72.5218,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
        ),
        PlaceModel(
          id: 'demo-rest-8',
          name: 'Tinello',
          description: 'Upscale contemporary Italian diner situated in the Hyatt Regency, featuring an open show kitchen, fresh handmade pasta, and executive business class dining.',
          category: 'Italian',
          budget: '₹₹₹',
          location: 'Ashram Road, Ahmedabad, Gujarat, India',
          rating: 4.7,
          isWishlist: false,
          isVisited: true,
          imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&auto=format&fit=crop',
          type: 'restaurant',
          latitude: 23.0441,
          longitude: 72.5714,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
        ),
        PlaceModel(
          id: 'demo-rest-9',
          name: 'Makeba',
          description: 'A stylish rooftop lounge boasting panoramic city views, live mocktail counters, and a global fusion menu featuring Mediterranean and Continental delicacies.',
          category: 'Continental',
          budget: '₹₹',
          location: 'SG Highway, Ahmedabad, Gujarat, India',
          rating: 4.4,
          isWishlist: true,
          isVisited: false,
          imageUrl: 'https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?w=600&auto=format&fit=crop',
          type: 'restaurant',
          latitude: 23.0510,
          longitude: 72.5122,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
        ),
        PlaceModel(
          id: 'demo-rest-10',
          name: 'Under The Neem Trees',
          description: 'An open-air garden cafe set beneath centuries-old Neem trees, specializing in healthy organic breakfast menus, cold-pressed juices, and single-origin coffee.',
          category: 'Café',
          budget: '₹₹',
          location: 'Sindhu Bhavan Road, Ahmedabad, Gujarat, India',
          rating: 4.5,
          isWishlist: false,
          isVisited: true,
          imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&auto=format&fit=crop',
          type: 'restaurant',
          latitude: 23.0425,
          longitude: 72.4965,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
        ),
      ];

  static List<PlaceModel> get clothingStores => [
        PlaceModel(
          id: 'demo-cloth-1',
          name: 'Zudio',
          description: 'A popular destination for hyper-affordable fast fashion apparel, footwear, and cosmetics for men, women, and kids with weekly-updating inventories.',
          category: 'Fast Fashion',
          budget: '₹',
          location: 'Prahladnagar, Ahmedabad, Gujarat, India',
          rating: 4.2,
          isWishlist: false,
          isVisited: true,
          imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600&auto=format&fit=crop',
          type: 'clothing',
          latitude: 23.0118,
          longitude: 72.5085,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
        ),
        PlaceModel(
          id: 'demo-cloth-2',
          name: 'Westside',
          description: 'Tata Group\'s premier lifestyle store offering contemporary, elegant in-house brands spanning wardrobe essentials, ethnic wear, footwear, and home decor.',
          category: 'Department Store',
          budget: '₹₹',
          location: 'CG Road, Ahmedabad, Gujarat, India',
          rating: 4.5,
          isWishlist: true,
          isVisited: false,
          imageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600&auto=format&fit=crop',
          type: 'clothing',
          latitude: 23.0310,
          longitude: 72.5615,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
        ),
        PlaceModel(
          id: 'demo-cloth-3',
          name: 'H&M',
          description: 'Swedish multinational retailer delivering high-quality global trends, everyday basics, and conscious sustainable fashion lines for all age demographics.',
          category: 'Casual Wear',
          budget: '₹₹',
          location: 'Palladium Mall, SG Highway, Ahmedabad, Gujarat, India',
          rating: 4.4,
          isWishlist: false,
          isVisited: true,
          imageUrl: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=600&auto=format&fit=crop',
          type: 'clothing',
          latitude: 23.0538,
          longitude: 72.5115,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
        ),
        PlaceModel(
          id: 'demo-cloth-4',
          name: 'Zara',
          description: 'A global high-street designer brand offering runway-inspired apparel, premium suits, outerwear, and sophisticated seasonal statement pieces.',
          category: 'Designer Boutique',
          budget: '₹Refined',
          location: 'Alpha One Mall, Vastrapur, Ahmedabad, Gujarat, India',
          rating: 4.6,
          isWishlist: true,
          isVisited: false,
          imageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&auto=format&fit=crop',
          type: 'clothing',
          latitude: 23.0402,
          longitude: 72.5275,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
        ),
        PlaceModel(
          id: 'demo-cloth-5',
          name: 'Pantaloons',
          description: 'One-stop family fashion retail store housing diverse styles of traditional ethnic, casual, sportswear, and kids apparel under one roof.',
          category: 'Department Store',
          budget: '₹₹',
          location: 'Satellite, Ahmedabad, Gujarat, India',
          rating: 4.1,
          isWishlist: false,
          isVisited: true,
          imageUrl: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=600&auto=format&fit=crop',
          type: 'clothing',
          latitude: 23.0285,
          longitude: 72.5298,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
        ),
        PlaceModel(
          id: 'demo-cloth-6',
          name: 'Trends',
          description: 'Reliance Retail\'s primary fashion brand featuring stylish contemporary ethnic wear and everyday casual wear with high affordability ratios.',
          category: 'Casual Wear',
          budget: '₹',
          location: 'Ghatlodia, Ahmedabad, Gujarat, India',
          rating: 4.0,
          isWishlist: true,
          isVisited: false,
          imageUrl: 'https://images.unsplash.com/photo-1479064555552-3ef4979f8908?w=600&auto=format&fit=crop',
          type: 'clothing',
          latitude: 23.0645,
          longitude: 72.5398,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
        ),
        PlaceModel(
          id: 'demo-cloth-7',
          name: 'Lifestyle',
          description: 'A stylish multi-brand store offering curated sections of trendsetting apparel, imported fragrances, makeup, and footwear accessories.',
          category: 'Department Store',
          budget: '₹₹',
          location: 'Nexus Ahmedabad One, Vastrapur, Gujarat, India',
          rating: 4.3,
          isWishlist: false,
          isVisited: true,
          imageUrl: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=600&auto=format&fit=crop',
          type: 'clothing',
          latitude: 23.0405,
          longitude: 72.5280,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
        ),
        PlaceModel(
          id: 'demo-cloth-8',
          name: 'Max Fashion',
          description: 'International brand providing an expansive catalog of casual, office, and infants apparel focused on maximum value and daily comfort.',
          category: 'Casual Wear',
          budget: '₹',
          location: 'Naranpura, Ahmedabad, Gujarat, India',
          rating: 4.2,
          isWishlist: true,
          isVisited: false,
          imageUrl: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=600&auto=format&fit=crop',
          type: 'clothing',
          latitude: 23.0585,
          longitude: 72.5482,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
        ),
        PlaceModel(
          id: 'demo-cloth-9',
          name: 'Shoppers Stop',
          description: 'India\'s leading premier fashion department store, retailing luxurious brands across beauty, watch design, footwear, and designer clothing tags.',
          category: 'Designer Boutique',
          budget: '₹Refined',
          location: 'Shivranjani Cross Roads, Ahmedabad, Gujarat, India',
          rating: 4.5,
          isWishlist: false,
          isVisited: true,
          imageUrl: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=600&auto=format&fit=crop',
          type: 'clothing',
          latitude: 23.0232,
          longitude: 72.5312,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
        ),
        PlaceModel(
          id: 'demo-cloth-10',
          name: 'Allen Solly',
          description: 'Pioneers of work-casual fashion wardrobes in India, offering vibrant Friday-dressing collection blazers, formals, and office shirts.',
          category: 'Formal Wear',
          budget: '₹₹',
          location: 'CG Road, Navrangpura, Ahmedabad, Gujarat, India',
          rating: 4.4,
          isWishlist: true,
          isVisited: false,
          imageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop',
          type: 'clothing',
          latitude: 23.0335,
          longitude: 72.5624,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
        ),
      ];

  static List<PlaceModel> get visits => [
        PlaceModel(
          id: 'demo-visit-1',
          name: 'Sabarmati Riverfront',
          description: 'A beautiful waterfront park project created along the banks of the Sabarmati River. Offers lush gardens, cycling tracks, speed boating, and peaceful evening walkways.',
          category: 'Park',
          budget: 'Free',
          location: 'Riverfront Road, Ahmedabad, Gujarat, India',
          rating: 4.7,
          isWishlist: false,
          isVisited: true,
          imageUrl: 'https://images.unsplash.com/photo-1595841696660-ab61cf40ef5a?w=600&auto=format&fit=crop',
          type: 'visit',
          latitude: 23.0392,
          longitude: 72.5785,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
          entryFee: 'Free',
          bestTime: 'October to March',
        ),
        PlaceModel(
          id: 'demo-visit-2',
          name: 'Adalaj Stepwell',
          description: 'A world-famous 5-story deep underground stepwell built in 1498. An architectural masterpiece displaying intricate Solanki carving designs, cool air shafts, and unique columns.',
          category: 'Historical',
          budget: 'Paid',
          location: 'Adalaj Road, Gandhinagar, Gujarat, India',
          rating: 4.8,
          isWishlist: true,
          isVisited: false,
          imageUrl: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=600&auto=format&fit=crop',
          type: 'visit',
          latitude: 23.1670,
          longitude: 72.5801,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
          entryFee: '₹20',
          bestTime: 'November to February',
        ),
        PlaceModel(
          id: 'demo-visit-3',
          name: 'Science City',
          description: 'An educational center showcasing a massive robotic gallery, aquatic gallery featuring sharks, IMAX screens, space simulator rides, and beautiful gardens.',
          category: 'Museum',
          budget: 'Paid',
          location: 'Science City Road, Sola, Ahmedabad, Gujarat, India',
          rating: 4.6,
          isWishlist: false,
          isVisited: true,
          imageUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=600&auto=format&fit=crop',
          type: 'visit',
          latitude: 23.0784,
          longitude: 72.4965,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
          entryFee: '₹50 onwards',
          bestTime: 'Year-round',
        ),
        PlaceModel(
          id: 'demo-visit-4',
          name: 'Kankaria Lake',
          description: 'A historic circular lake created in 1451. Features a balloon safari, kids-city play museum, toy train, stone-carved walkways, zoo, and nightly musical laser fountains.',
          category: 'Lake',
          budget: 'Paid',
          location: 'Maninagar, Ahmedabad, Gujarat, India',
          rating: 4.5,
          isWishlist: false,
          isVisited: true,
          imageUrl: 'https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?w=600&auto=format&fit=crop',
          type: 'visit',
          latitude: 23.0062,
          longitude: 72.5998,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
          entryFee: '₹20',
          bestTime: 'October to April',
        ),
        PlaceModel(
          id: 'demo-visit-5',
          name: 'Statue of Unity',
          description: 'The tallest monument statue in the world, depicting Indian statesman Vallabhbhai Patel. Set near the Sardar Sarovar Dam with panoramic river decks and flower valleys.',
          category: 'Monument',
          budget: 'Paid',
          location: 'Kevadia, Narmada District, Gujarat, India',
          rating: 4.9,
          isWishlist: true,
          isVisited: false,
          imageUrl: 'https://images.unsplash.com/photo-1620121692029-d088224ddc74?w=600&auto=format&fit=crop',
          type: 'visit',
          latitude: 21.8380,
          longitude: 73.7191,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
          entryFee: '₹150 onwards',
          bestTime: 'October to March',
        ),
        PlaceModel(
          id: 'demo-visit-6',
          name: 'Gir National Park',
          description: 'The exclusive home and sanctuary of the majestic wild Asiatic Lions. Home to diverse populations of leopards, antelopes, marsh crocodiles, and rare birds.',
          category: 'Nature',
          budget: 'Paid',
          location: 'Sasan Gir, Junagadh District, Gujarat, India',
          rating: 4.8,
          isWishlist: false,
          isVisited: true,
          imageUrl: 'https://images.unsplash.com/photo-1615959189197-484c0fcab8c1?w=600&auto=format&fit=crop',
          type: 'visit',
          latitude: 21.1243,
          longitude: 70.7948,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
          entryFee: '₹800 (jeep safari)',
          bestTime: 'December to March',
        ),
        PlaceModel(
          id: 'demo-visit-7',
          name: 'Rani Ki Vav',
          description: 'An exquisitely constructed UNESCO World Heritage stepwell built in 11th century. Represents peak subterranean water-conservation art with over 500 major sculptures.',
          category: 'Historical',
          budget: 'Paid',
          location: 'Patan, North Gujarat, India',
          rating: 4.9,
          isWishlist: true,
          isVisited: false,
          imageUrl: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=600&auto=format&fit=crop',
          type: 'visit',
          latitude: 23.8587,
          longitude: 72.1018,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
          entryFee: '₹40',
          bestTime: 'October to February',
        ),
        PlaceModel(
          id: 'demo-visit-8',
          name: 'Polo Forest',
          description: 'A beautiful forest retreat filled with ancient 15th-century Hindu and Jain temple ruins, river pools, dense green canopy hikes, and bird-watching hotspots.',
          category: 'Nature',
          budget: 'Free',
          location: 'Vijaynahar, Sabarkantha District, Gujarat, India',
          rating: 4.6,
          isWishlist: false,
          isVisited: true,
          imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&auto=format&fit=crop',
          type: 'visit',
          latitude: 23.9575,
          longitude: 73.2382,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
          entryFee: 'Free',
          bestTime: 'July to October (Monsoon)',
        ),
        PlaceModel(
          id: 'demo-visit-9',
          name: 'Somnath Temple',
          description: 'A sacred shore-side jyotirlinga temple showcasing gorgeous Chalukyan architecture. Reconstructed multiple times throughout history, offering spectacular evening light shows.',
          category: 'Temple',
          budget: 'Free',
          location: 'Somnath Patan, Prabhas Patan, Gujarat, India',
          rating: 4.9,
          isWishlist: true,
          isVisited: false,
          imageUrl: 'https://images.unsplash.com/photo-1604537529428-15bcbeecfe4d?w=600&auto=format&fit=crop',
          type: 'visit',
          latitude: 20.8880,
          longitude: 70.4012,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
          entryFee: 'Free',
          bestTime: 'October to March',
        ),
        PlaceModel(
          id: 'demo-visit-10',
          name: 'White Desert',
          description: 'The legendary Great Rann of Kutch, one of the largest salt deserts in the world. Famous for its white salt flats shining brightly under full moon nights.',
          category: 'Nature',
          budget: 'Paid',
          location: 'Dhordo, Kutch District, Gujarat, India',
          rating: 4.8,
          isWishlist: false,
          isVisited: true,
          imageUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=600&auto=format&fit=crop',
          type: 'visit',
          latitude: 23.7845,
          longitude: 69.8550,
          dateAdded: '2026-07-10',
          lastUpdated: '2026-07-10 10:00',
          imageType: 'network',
          isDemoData: true,
          entryFee: '₹100',
          bestTime: 'November to February (Rann Utsav)',
        ),
      ];

  static List<PlaceModel> get all => [
        ...restaurants,
        ...clothingStores,
        ...visits,
      ];
}
